name: Build Blog

on:
  push:
    branches: [ main ]
    paths: [ 'posts/*.html' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build blog pages
      run: ./build.sh
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html posts/all.html
        git diff --staged --quiet || git commit -m "Auto-build blog pages"
        git push