name: Build Blog

on:
  push:
    branches: [ main ]
    paths: [ 'posts/*.html' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build blog pages
      run: ./build.sh
    
    - name: Prepare deployment directory
      run: |
        mkdir -p deploy/posts
        cp index.html deploy/
        cp posts/all.html deploy/posts/
        cp style.css deploy/
        cp CNAME deploy/
        cp posts/*.html deploy/posts/ 2>/dev/null || true
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: deploy
        publish_branch: gh-pages
        keep_files: false